name: time_series_analyzer
description: a grpc microservice that performs FFTs on the output from the timeseries generator and outputs short time PSDs
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  fftea: ^1.3.1
  async: ^2.2.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
